import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/core/nav";
import Footer from "@/components/core/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen prose-h1:prose-2xl`}
      >
        <Nav />
        <main className="grow mt-14 container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
